language: csharp
solution: DeJson.NET.sln
install:
  - nuget restore DeJson.NET.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DeJson.NET.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DeJsonTest/bin/Release/DeJsonTest.dll

